server:
  port: 8081

spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/finsight_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Custom JWT configuration
finsight:
  jwt:
    # 256-bit Base64-encoded secret key
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours (86,400,000 ms)
    refresh-expiration-ms: 604800000 # 7 days (604,800,000 ms)
  admin:
    username: ${DEFAULT_ADMIN_USER:admin}
    email: ${DEFAULT_ADMIN_EMAIL:admin@finsight.com}
    password: ${DEFAULT_ADMIN_PASSWORD:AdminPass123!}

logging:
  level:
    com.finsight.backend: DEBUG
